/* Generated by Yosys 0.45+106 (git sha1 982fade0d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module cdc(in, clk, rst_n, qb2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input clk;
  wire clk;
  input [4:0] in;
  wire [4:0] in;
  wire [4:0] qb1;
  output [4:0] qb2;
  wire [4:0] qb2;
  input rst_n;
  wire rst_n;
  AND2_X1 _20_ (
    .A1(in[3]),
    .A2(rst_n),
    .ZN(_00_)
  );
  AND2_X1 _21_ (
    .A1(rst_n),
    .A2(in[2]),
    .ZN(_01_)
  );
  AND2_X1 _22_ (
    .A1(rst_n),
    .A2(in[1]),
    .ZN(_02_)
  );
  AND2_X1 _23_ (
    .A1(rst_n),
    .A2(in[0]),
    .ZN(_03_)
  );
  AND2_X1 _24_ (
    .A1(rst_n),
    .A2(qb1[3]),
    .ZN(_04_)
  );
  AND2_X1 _25_ (
    .A1(rst_n),
    .A2(qb1[2]),
    .ZN(_05_)
  );
  AND2_X1 _26_ (
    .A1(rst_n),
    .A2(qb1[1]),
    .ZN(_06_)
  );
  AND2_X1 _27_ (
    .A1(rst_n),
    .A2(qb1[0]),
    .ZN(_07_)
  );
  AND2_X1 _28_ (
    .A1(rst_n),
    .A2(qb1[4]),
    .ZN(_08_)
  );
  AND2_X1 _29_ (
    .A1(rst_n),
    .A2(in[4]),
    .ZN(_09_)
  );
  DFF_X1 _30_ (
    .CK(clk),
    .D(_07_),
    .Q(qb2[0]),
    .QN(_12_)
  );
  DFF_X1 _31_ (
    .CK(clk),
    .D(_06_),
    .Q(qb2[1]),
    .QN(_13_)
  );
  DFF_X1 _32_ (
    .CK(clk),
    .D(_05_),
    .Q(qb2[2]),
    .QN(_14_)
  );
  DFF_X1 _33_ (
    .CK(clk),
    .D(_04_),
    .Q(qb2[3]),
    .QN(_15_)
  );
  DFF_X1 _34_ (
    .CK(clk),
    .D(_08_),
    .Q(qb2[4]),
    .QN(_11_)
  );
  DFF_X1 _35_ (
    .CK(clk),
    .D(_03_),
    .Q(qb1[0]),
    .QN(_16_)
  );
  DFF_X1 _36_ (
    .CK(clk),
    .D(_02_),
    .Q(qb1[1]),
    .QN(_17_)
  );
  DFF_X1 _37_ (
    .CK(clk),
    .D(_01_),
    .Q(qb1[2]),
    .QN(_18_)
  );
  DFF_X1 _38_ (
    .CK(clk),
    .D(_00_),
    .Q(qb1[3]),
    .QN(_19_)
  );
  DFF_X1 _39_ (
    .CK(clk),
    .D(_09_),
    .Q(qb1[4]),
    .QN(_10_)
  );
endmodule
