/* Generated by Yosys 0.45+106 (git sha1 982fade0d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module b2g(b, g);
  input [4:0] b;
  wire [4:0] b;
  output [4:0] g;
  wire [4:0] g;
  XOR2_X1 _0_ (
    .A(b[1]),
    .B(b[0]),
    .Z(g[0])
  );
  XOR2_X1 _1_ (
    .A(b[4]),
    .B(b[3]),
    .Z(g[3])
  );
  XOR2_X1 _2_ (
    .A(b[3]),
    .B(b[2]),
    .Z(g[2])
  );
  XOR2_X1 _3_ (
    .A(b[1]),
    .B(b[2]),
    .Z(g[1])
  );
  assign g[4] = b[4];
endmodule

module rptr_handler(g_wptr, rclk, rrst_n, r_en, raddr, rptr, empty);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  output empty;
  wire empty;
  wire [4:0] g_rptr_next;
  input [4:0] g_wptr;
  wire [4:0] g_wptr;
  input r_en;
  wire r_en;
  output [3:0] raddr;
  wire [3:0] raddr;
  wire [4:0] rbin;
  wire [4:0] rbin_next;
  input rclk;
  wire rclk;
  wire rempty;
  output [4:0] rptr;
  wire [4:0] rptr;
  input rrst_n;
  wire rrst_n;
  INV_X1 _25_ (
    .A(rbin[1]),
    .ZN(_06_)
  );
  INV_X1 _26_ (
    .A(g_rptr_next[3]),
    .ZN(_07_)
  );
  INV_X1 _27_ (
    .A(g_rptr_next[1]),
    .ZN(_08_)
  );
  INV_X1 _28_ (
    .A(g_wptr[0]),
    .ZN(_09_)
  );
  INV_X1 _29_ (
    .A(g_rptr_next[4]),
    .ZN(_10_)
  );
  NAND2_X1 _30_ (
    .A1(r_en),
    .A2(_05_),
    .ZN(_11_)
  );
  NAND3_X1 _31_ (
    .A1(rbin[0]),
    .A2(r_en),
    .A3(_05_),
    .ZN(_12_)
  );
  NOR2_X1 _32_ (
    .A1(_06_),
    .A2(_12_),
    .ZN(_13_)
  );
  NAND2_X1 _33_ (
    .A1(rbin[2]),
    .A2(_13_),
    .ZN(_14_)
  );
  NAND3_X1 _34_ (
    .A1(rbin[2]),
    .A2(rbin[3]),
    .A3(_13_),
    .ZN(_15_)
  );
  XNOR2_X1 _35_ (
    .A(rbin[4]),
    .B(_15_),
    .ZN(rbin_next[4])
  );
  XNOR2_X1 _36_ (
    .A(rbin[3]),
    .B(_14_),
    .ZN(rbin_next[3])
  );
  XOR2_X1 _37_ (
    .A(rbin[2]),
    .B(_13_),
    .Z(rbin_next[2])
  );
  XNOR2_X1 _38_ (
    .A(rbin[1]),
    .B(_12_),
    .ZN(rbin_next[1])
  );
  XNOR2_X1 _39_ (
    .A(rbin[0]),
    .B(_11_),
    .ZN(rbin_next[0])
  );
  OAI222_X1 _40_ (
    .A1(_07_),
    .A2(g_wptr[3]),
    .B1(_08_),
    .B2(g_wptr[1]),
    .C1(_10_),
    .C2(g_wptr[4]),
    .ZN(_16_)
  );
  AOI222_X1 _41_ (
    .A1(_07_),
    .A2(g_wptr[3]),
    .B1(_08_),
    .B2(g_wptr[1]),
    .C1(g_rptr_next[0]),
    .C2(_09_),
    .ZN(_17_)
  );
  XNOR2_X1 _42_ (
    .A(g_rptr_next[2]),
    .B(g_wptr[2]),
    .ZN(_18_)
  );
  OAI211_X1 _43_ (
    .A(_17_),
    .B(_18_),
    .C1(g_rptr_next[0]),
    .C2(_09_),
    .ZN(_19_)
  );
  AOI211_X1 _44_ (
    .A(_16_),
    .B(_19_),
    .C1(_10_),
    .C2(g_wptr[4]),
    .ZN(rempty)
  );
  DFFS_X1 _45_ (
    .CK(rclk),
    .D(rempty),
    .Q(empty),
    .QN(_05_),
    .SN(rrst_n)
  );
  DFFR_X1 _46_ (
    .CK(rclk),
    .D(g_rptr_next[0]),
    .Q(rptr[0]),
    .QN(_23_),
    .RN(rrst_n)
  );
  DFFR_X1 _47_ (
    .CK(rclk),
    .D(g_rptr_next[1]),
    .Q(rptr[1]),
    .QN(_22_),
    .RN(rrst_n)
  );
  DFFR_X1 _48_ (
    .CK(rclk),
    .D(g_rptr_next[2]),
    .Q(rptr[2]),
    .QN(_21_),
    .RN(rrst_n)
  );
  DFFR_X1 _49_ (
    .CK(rclk),
    .D(g_rptr_next[3]),
    .Q(rptr[3]),
    .QN(_20_),
    .RN(rrst_n)
  );
  DFFR_X1 _50_ (
    .CK(rclk),
    .D(g_rptr_next[4]),
    .Q(rptr[4]),
    .QN(_24_),
    .RN(rrst_n)
  );
  DFFR_X1 _51_ (
    .CK(rclk),
    .D(rbin_next[0]),
    .Q(rbin[0]),
    .QN(_04_),
    .RN(rrst_n)
  );
  DFFR_X1 _52_ (
    .CK(rclk),
    .D(rbin_next[1]),
    .Q(rbin[1]),
    .QN(_03_),
    .RN(rrst_n)
  );
  DFFR_X1 _53_ (
    .CK(rclk),
    .D(rbin_next[2]),
    .Q(rbin[2]),
    .QN(_02_),
    .RN(rrst_n)
  );
  DFFR_X1 _54_ (
    .CK(rclk),
    .D(rbin_next[3]),
    .Q(rbin[3]),
    .QN(_01_),
    .RN(rrst_n)
  );
  DFFR_X1 _55_ (
    .CK(rclk),
    .D(rbin_next[4]),
    .Q(rbin[4]),
    .QN(_00_),
    .RN(rrst_n)
  );
  b2g gray_converter2 (
    .b(rbin_next),
    .g(g_rptr_next)
  );
  assign raddr = rbin[3:0];
endmodule
